### ISSUE TITLE
I can not take Token

### ISSUE THREAD

**Issue by pudrapembesi95** [zhuowei/ClubhouseAPI#1]
I can not take Token from **_complete_phone_number_auth, start_phone_number_auth APIs_**, but APIs return 400 when I make a request

**Header;**
Content-Type:application/json
User-Agent:Clubhouse
CH-Locale:en_US
CH-AppVersion:0.2.15
CH-AppBuild:269

**Body;**
{
    "jsonObject": {
        "value": {
            "phone_number": "+11234567890" 
        }
    }
}

How can I get my token ?

**Comment by zhuowei** [comment]
The body's just `{"phone_number": "+11234567890"}`
